version: ~> 1.0

language: java
os: linux
dist: bionic

jdk:
  - openjdk8
  - openjdk11

script:
  - ./gradlew assemble
  - ./gradlew check
  - cd "${TRAVIS_BUILD_DIR}/manual-test/" && ./gradlew clean build
  - cd "${TRAVIS_BUILD_DIR}/manual-test-2/" && ./gradlew clean build
  - cd "${TRAVIS_BUILD_DIR}/usage/" && ./gradlew clean build
  - cd "${TRAVIS_BUILD_DIR}"

deploy:
  - provider: script
    script: echo "version=${TRAVIS_TAG}" > build.properties && ./gradlew publishPlugins -Pgradle.publish.key="${GRADLE_PUBLISH_KEY}" -Pgradle.publish.secret="${GRADLE_PUBLISH_SECRET}"
    skip_cleanup: true
    on:
      tags: true
      repo: Heapy/heapy-kotlin-repositories-gradle-plugin
      jdk: openjdk8

